name: Check notification

on: [push]

jobs:
  notifications:
    name: Rocket.Chat Notifications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: with mention
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success*'
          mention: 'here'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: with mention on success
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success*'
          mention: 'here'
          mention_if: 'success'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: with mention on always
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success*'
          mention: 'here'
          mention_if: 'success'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: with mention on failure only
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success no mention*'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: with no mention
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success no mention*'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: with commit info
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Commit*'
          commit: 'true'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
